### ISSUE TITLE
Added to themes list

### ISSUE THREAD

**Issue by retr0h** [rjayasinghe/hugo-nes-classic#1]
Could you create a screen shot much like the other themes and add it to the [hugo list](https://themes.gohugo.io/)?

P.S. I was hoping someone would create a hugo theme with NES.css :) Thanks! \m/

**Comment by retr0h** [comment]
@rjayasinghe

![tenor-218513069](https://user-images.githubusercontent.com/9895/54078896-a05c5500-4285-11e9-89e5-98a445b84d47.gif)

**Comment by rjayasinghe** [comment]
haha.. I could do this. But it has to wait till the weekend. This is my first Hugo theme. The layout (positioning of menu etc.) is really simple and kind of oldschool. ;)

**Comment by rjayasinghe** [comment]
So, it took a while (family first). I had to perform some work on the theme to make it ready, but now it's up the maintainers of the Hugo theme list. https://github.com/gohugoio/hugoThemes/issues/625

**Comment by rjayasinghe** [comment]
https://t.co/2KK87ckUyQ
